from models.event import Event


class BarEvent(Event):
    """
       The BarEvent class inherits from the Event class and represents a specific type of event: a bar event.
        A bar event is an event that takes place in a bar and has a bar profit and an artist payment.
    """

    def __init__(self, name, date, opening_time, show_time, location, address, city, artists, capacity):
        super().__init__(name, date, opening_time, show_time, location, address, city, artists, capacity)
        self.bar_profit = 0.2  # The profit generated by the bar during the event
        self.artist_payment = 0.8  # The payment for the artist performing at the event
